### ISSUE TITLE
rush: invalid option -- 'j'

### ISSUE THREAD

**Issue by welltest** [KingOfBugbounty/KingOfBugBountyTips#14]
curl -s "https://jldc.me/anubis/subdomains/sony.com" | grep -Po "((http|https):\/\/)?(([\w.-]*)\.([\w]*)\.([A-z]))\w+" | httpx -silent -threads 300 | anew | rush -j 10 'jaeles scan -s /jaeles-signatures/ -u {}'

**Comment by KingOfBugbounty** [comment]
![image](https://user-images.githubusercontent.com/28729614/92740682-f19e4680-f34b-11ea-881b-9d643b0eee5e.png)
