### ISSUE TITLE
where can I find these scripts?

### ISSUE THREAD

**Issue by kesonn** [KingOfBugbounty/KingOfBugBountyTips#33]
![image](https://user-images.githubusercontent.com/36539433/127818649-a6a85637-df5d-4304-b389-725ac21565b5.png)
where can I find these scripts?
collector.py, SecretFinder.py.

**Comment by sukenn** [comment]
https://github.com/m4ll0k/SecretFinder
https://github.com/m4ll0k/BBTz/blob/master/collector.py

**Comment by KingOfBugbounty** [comment]
Thanks @sukenn !
