### ISSUE TITLE
command not runing

### ISSUE THREAD

**Issue by Sharmitanmay** [KingOfBugbounty/KingOfBugBountyTips#34]
assetfinder fitbit.com | httpx -threads 300 -follow-redirects -silent | rush -j200 'curl -m5 -s -I -H "Origin:evil.com" {} |  [[ $(grep -c "evil.com") -gt 0 ]] && printf "\n\033[0;32m[VUL TO CORS] - {}\e[m"' 2>/dev/null"

please check this command:

![image](https://user-images.githubusercontent.com/60282451/132337394-18a0451c-616d-44c7-a2d7-0a9e4b59c355.png)

**Comment by KingOfBugbounty** [comment]
assetfinder fitbit.com | httpx -threads 300 -follow-redirects -silent | rush -j100 'curl -m5 -s -I -H "Origin:evil.com" {} | [[ $(grep -c "evil.com") -gt 0 ]] && printf "\n\033[0;32m[VUL TO CORS] - {}\e[m"'
